# Generated by Django 4.2 on 2023-07-25 15:57

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_ategory',
            new_name='post_category',
        ),
        migrations.AddField(
            model_name='post',
            name='details',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
