# Generated by Django 4.2 on 2023-07-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_post_view_count_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
