# Generated by Django 4.2 on 2023-07-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_addvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvideo',
            name='title',
            field=models.CharField(default='Hi', max_length=200),
        ),
    ]
